import { writeText } from '../../shared/lib/fs.ts';
import { readFileSync } from 'node:fs';
import type { Config } from '../../shared/lib/config.ts';
import { log } from '../../shared/lib/logger.ts';
import { OpenRouterClient } from '../../shared/lib/openrouter.ts';
import { getRouting } from '../../shared/lib/models.ts';
import type { Spec } from '../../shared/types/index.ts';
import type { TestCaseFile } from '../test-case-gen/agent.ts';
import type { ModelRouting } from '../../shared/lib/models.ts';

export interface CodegenResult {
  files: string[];
  provider: string;
  warnings: string[];
}

const TSC_PATTERN = /\.spec\.ts$/;

/**
 * Agent 5 — Automation Codegen.
 * Approved test cases → .spec.ts page objects that follow the framework profile
 * (tests/framework-profile.json). Output must pass tsc --noEmit and execute.
 */
export class AutomationCodegenAgent {
  private cfg: Config;
  private llm: OpenRouterClient;
  private routing: ModelRouting;

  constructor(cfg: Config) {
    this.cfg = cfg;
    this.llm = new OpenRouterClient(this.cfg);
    this.routing = getRouting(this.cfg);
  }

  async run(tests: TestCaseFile, spec: Spec): Promise<CodegenResult> {
    const frameworkProfile = this.readProfile();
    const generatedDir = `${this.cfg.rootDir}/tests/generated`;
    const files: string[] = [];
    const warnings: string[] = [];

    const specLocators = this.buildLocatorMap(spec);

    let content: string;
    let provider: string;
    if (this.llm.configured) {
      try {
        const res = await this.llm.chat({
          model: this.routing.automationCodegen,
          messages: [
            { role: 'system', content: `You are a senior Playwright + TypeScript test engineer. Generate a single .spec.ts file that matches the project framework profile exactly (imports, baseUrl, POM usage, naming). Use only element ids/locators provided. Output ONLY the TypeScript file content, no fences, no commentary.` },
            { role: 'user', content: `Framework profile:\n${JSON.stringify(frameworkProfile, null, 2)}\n\nTest cases (Gherkin):\n${tests.cases.map((c) => `## ${c.title} (${c.priority})\n${c.scenario}\n${c.steps.map((s) => `- ${s.action} ${s.target ?? ''}`).join('\n')}\nExpect: ${c.expected}`).join('\n\n')}\n\nElement locators:\n${JSON.stringify(specLocators, null, 2)}\n\nWrite a single ${tests.screenId}.spec.ts that imports from the framework profile's test base.` },
          ],
          temperature: 0,
          maxTokens: 6000,
        });
        provider = this.routing.automationCodegen;
        content = res.content.replace(/^```(?:typescript|ts)?\s*/i, '').replace(/\s*```$/, '');
      } catch (err) {
        log.warn('automation-codegen', `LLM failed (${(err as Error).message}); using template generator`);
        content = this.templateSpec(tests, specLocators, frameworkProfile);
        provider = 'template';
        warnings.push('LLM unavailable — used deterministic template generator');
      }
    } else {
      log.info('automation-codegen', 'no OPENROUTER_API_KEY; using template generator');
      content = this.templateSpec(tests, specLocators, frameworkProfile);
      provider = 'template';
    }

    const filePath = `${generatedDir}/${tests.screenId}.spec.ts`;
    writeText(filePath, content);
    files.push(filePath);

    log.info('automation-codegen', `wrote ${filePath} (provider: ${provider})`);
    return { files, provider, warnings };
  }

  private readProfile(): { testDir: string; baseUrl: string; importFrom: string; use: Record<string, unknown> } {
    try {
      const p = `${this.cfg.rootDir}/tests/framework-profile.json`;
      return JSON.parse(readFileSync(p, 'utf-8'));
    } catch {
      return {
        testDir: './tests/generated',
        baseUrl: 'http://localhost:3000',
        importFrom: '@playwright/test',
        use: {},
      };
    }
  }

  private buildLocatorMap(spec: Spec): Record<string, string> {
    const map: Record<string, string> = {};
    for (const el of spec.elements) {
      const loc = el.locator?.testId
        ? `[data-testid="${el.locator.testId}"]`
        : el.locator?.css
          ? el.locator.css
          : el.text
            ? `text=${el.text}`
            : el.a11y?.label
              ? `getByLabel:${el.a11y.label}`
              : el.id;
      map[el.id] = loc;
    }
    return map;
  }

  private templateSpec(tests: TestCaseFile, locators: Record<string, string>, profile: { importFrom: string; baseUrl: string; testDir: string; use: Record<string, unknown> }): string {
    const t = profile.importFrom || '@playwright/test';
    const baseUrl = profile.baseUrl || 'http://localhost:3000';
    const lines: string[] = [
      `// Generated by Automation Codegen Agent (${tests.screenId}) — do not edit by hand.`,
      `import { test, expect } from '${t}';`,
      ``,
      `test.describe('${tests.screenId}', () => {`,
      `  test.beforeEach(async ({ page }) => {`,
      `    await page.goto('${baseUrl}');`,
      `  });`,
      ``,
    ];

    const locExpr = (loc: string): string => {
      if (loc.startsWith('getByLabel:')) return `page.getByLabel('${this.esc(loc.slice('getByLabel:'.length))}')`;
      return `page.locator('${this.esc(loc)}')`;
    };

    for (const c of tests.cases) {
      lines.push(`  test('${this.esc(c.title)}', async ({ page }) => {`);
      for (const s of c.steps) {
        const loc = locators[s.target ?? ''] ?? s.target ?? '';
        const el = locExpr(loc);
        switch (s.action) {
          case 'click':
            lines.push(`    await ${el}.click();`);
            break;
          case 'input':
            lines.push(`    await ${el}.fill('${this.esc(s.value ?? 'test-value')}');`);
            break;
          case 'assertVisible':
            lines.push(`    await expect(${el}).toBeVisible();`);
            break;
          case 'assertText':
            lines.push(`    await expect(${el}).toContainText('${this.esc(s.value ?? '')}');`);
            break;
          default:
            lines.push(`    // step: ${s.action} on ${s.target ?? ''}`);
        }
      }
      lines.push(`  });`);
      lines.push(``);
    }

    lines.push(`});`);
    lines.push(``);
    return lines.join('\n');
  }

  private esc(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }
}

export function isSpecFile(p: string): boolean {
  return TSC_PATTERN.test(p);
}
