"use client";

import { useEffect, useState } from "react";
import { Loader2, Trash2, Plus, TestTube } from "lucide-react";
import PageChrome from "@/components/ui/PageChrome";
import Button from "@/components/ui/Button";
import { GroupListSkeleton } from "@/components/ui/Skeleton";
import { invalidateListCaches, useListSWR } from "@/lib/use-list-swr";

type Project = { id: string; name: string; description: string | null; jiraUrl: string | null; createdAt: string; testCases: number };
type ProjectsResponse = { projects: Project[] };

export default function TestProjectsPage() {
  const { data, error, isLoading, mutate } = useListSWR<ProjectsResponse>("/api/projects");
  const [showNew, setShowNew] = useState(false); const [name, setName] = useState(""); const [desc, setDesc] = useState(""); const [jiraUrl, setJiraUrl] = useState(""); const [saving, setSaving] = useState(false);
  const projects = data?.projects || [];
  const createProject = async () => { if (!name.trim()) return; setSaving(true); try { const res = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description: desc, jiraUrl }) }); if (res.ok) { setName(""); setDesc(""); setJiraUrl(""); setShowNew(false); await invalidateListCaches(); await mutate(); } } finally { setSaving(false); } };
  const deleteProject = async (id: string) => { if (!confirm("Delete this project?")) return; const res = await fetch(`/api/projects/${id}`, { method: "DELETE" }); if (res.ok) { await invalidateListCaches(); await mutate(); } };
  return <PageChrome maxWidthClass="max-w-5xl" header={<div className="flex items-center justify-between gap-3"><div><h1 className="text-lg font-semibold tracking-tight text-text-primary">Projects</h1><p className="mt-1 text-sm text-text-muted">Manage test analysis projects and generated cases.</p></div><Button size="sm" onClick={() => setShowNew(!showNew)}><Plus size={15} />New project</Button></div>}><div className="space-y-4 pb-8">{showNew && <div className="rounded-xl border border-border bg-white p-5 shadow-sm space-y-3"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Project name" className="w-full rounded-lg border border-border-input bg-bg-input px-3 py-2 text-sm outline-none focus:border-border-focus" /><textarea value={desc} onChange={(e) => setDesc(e.target.value)} placeholder="Description (optional)" rows={2} className="w-full resize-none rounded-lg border border-border-input bg-bg-input px-3 py-2 text-sm outline-none focus:border-border-focus" /><input value={jiraUrl} onChange={(e) => setJiraUrl(e.target.value)} placeholder="JIRA URL (optional)" className="w-full rounded-lg border border-border-input bg-bg-input px-3 py-2 text-sm outline-none focus:border-border-focus" /><Button onClick={createProject} disabled={saving}>{saving && <Loader2 size={15} className="animate-spin" />}Create project</Button></div>}{error ? <div className="rounded-xl border border-border bg-white p-12 text-center text-sm text-red-600">Failed to load projects.</div> : isLoading && !data ? <GroupListSkeleton /> : projects.length === 0 ? <div className="rounded-xl border border-border bg-white p-16 text-center"><TestTube size={30} className="mx-auto mb-3 text-amber-500" /><p className="font-medium text-text-primary">No projects yet</p><p className="mt-1 text-sm text-text-muted">Create one to organize test cases.</p></div> : <div className="grid gap-3 md:grid-cols-2">{projects.map((project) => <div key={project.id} className="group rounded-xl border border-border bg-white p-4 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-text-primary">{project.name}</p><p className="mt-1 text-xs text-text-muted">{project.testCases} test cases · Created {new Date(project.createdAt).toLocaleDateString()}</p></div><button onClick={() => deleteProject(project.id)} className="rounded-md p-1.5 text-text-muted hover:bg-red-50 hover:text-red-500"><Trash2 size={15} /></button></div>{project.description && <p className="mt-3 text-sm leading-relaxed text-text-secondary">{project.description}</p>}</div>)}</div>}</div></PageChrome>;
}
