# Topic list for Mom & Son cartoon videos.
# Each entry is a short, self-contained teaching topic.
# The script generator turns one of these into a full scene-by-scene script.

TOPICS = [
    # --- Vegetables ---
    "Why carrots are good for your eyes",
    "Broccoli makes you strong",
    "Spinach gives you energy like Popeye",
    "Potatoes give you energy for playing",
    "Tomatoes keep your heart healthy",
    "Cucumber keeps you cool and hydrated",
    "Peas are little green power balls",
    "Corn is sweet sunshine food",
    "Bell peppers come in rainbow colors and are full of vitamins",
    "Pumpkin helps you see in the dark",
    "Beetroot makes your cheeks pink and strong",
    "Cauliflower is a white flower of health",
    "Onions make food yummy and keep you healthy",
    "Okra (bhindi) is a slimy super veggie",
    "Bitter gourd (karela) cleans your blood even if it's bitter",
    "Bottle gourd (lauki) is light and good for tummy",
    "Brinjal (baingan) is the purple prince of vegetables",
    "Radish is crunchy and good for digestion",
    "Green beans are little healthy sticks",
    "Cabbage has layers of goodness",
    "Lettuce makes yummy salads that keep you fit",
    "Mushrooms make you strong like a superhero",
    "Asparagus is a springtime veggie treat",
    "Zucchini is a friendly green squash",
    "Sweet potato is nature's candy that's good for you",
    "Turnips are crunchy winter veggies",
    "Fenugreek (methi) leaves are bitter but full of iron",
    "Colocasia (arbi) is a tasty taro treat",
    "Drumsticks (saijan) make bones strong",
    "Fennel (saunf) helps you digest food",

    # --- Fruits ---
    "Apples keep the doctor away",
    "Bananas give you instant energy for sports",
    "Oranges are full of vitamin C to fight colds",
    "Mango is the king of fruits and full of vitamins",
    "Watermelon keeps you hydrated in summer",
    "Strawberries are sweet heart berries",
    "Grapes are tiny bunches of energy",
    "Pineapple helps your tummy digest food",
    "Papaya is great for your stomach",
    "Pomegranate (anar) gives you red blood and strength",
    "Guava is cheap and full of vitamin C",
    "Kiwi is a fuzzy green vitamin bomb",
    "Blueberries make your brain super smart",
    "Peaches are fuzzy and full of goodness",
    "Cherries are tiny red treats for your heart",
    "Plums are sweet summer fruits",
    "Lychee is a sweet summer treat",
    "Coconut water is nature's sports drink",
    "Avocado is creamy healthy fat for your brain",
    "Pear is juicy and good for your throat",
    "Muskmelon (kharbooja) is sweet and cooling",
    "Jackfruit is the giant of fruits and full of protein",
    "Custard apple (sitaphal) is nature's ice cream",
    "Dates give you instant energy",
    "Figs (anjeer) make bones strong",
    "Sapota (chikoo) is sweet and gives energy",
    "Dragon fruit is a pretty pink superfruit",
    "Raspberries are tart little vitamin treats",
    "Blackberries are dark purple power berries",
    "Cranberries keep your tummy happy",

    # --- Foods / Healthy habits ---
    "Milk makes bones and teeth strong",
    "Yogurt (dahi) is good for your tummy",
    "Eggs are a powerhouse of protein",
    "Oats give you slow energy all morning",
    "Nuts and almonds make your brain sharp",
    "Honey is nature's sweet medicine",
    "Whole wheat roti gives you fiber and energy",
    "Rice gives you energy for the whole day",
    "Lentils (dal) are protein-packed and filling",
    "Chickpeas (chole) make muscles strong",
    "Cheese is a tasty calcium treat",
    "Peanut butter gives you healthy fats",
    "Green tea is a gentle healthy drink",
    "Drinking water keeps you fresh and healthy",
    "Breakfast is the most important meal of the day",
    "Eating seasonal fruits and veggies is smart",
    "Washing fruits before eating keeps you safe",
    "Too much sugar is bad for your teeth",
    "Junk food sometimes is okay but not always",
    "Homemade food is love and health",
    "Salad makes your plate colorful and healthy",
    "Eating slowly helps you digest better",
    "Chewing food well is good for your tummy",
    "Sitting together for meals makes food tastier",
    "Sprouts are tiny living food full of protein",
    "Ragi (finger millet) makes bones and brain strong",
    "Ghee is good for your brain in small amounts",
    "Turmeric milk is the golden drink for immunity",
    "Ajwain water helps a sore tummy",
    "Eating colorful food gives you all vitamins",
]

if __name__ == "__main__":
    print(f"{len(TOPICS)} topics loaded")
