import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Config } from '../config.js';
import { OpenRouterClient } from '../llm/openrouter.js';
import { FigmaMcp } from '../figma/figmaMcp.js';
import { fetchFigmaMaterial } from '../figma/loader.js';
import { AnalysisAgent } from '../agents/analysisAgent.js';
import { TestCaseAgent } from '../agents/testCaseAgent.js';
import { AutomationAgent } from '../agents/automationAgent.js';
import { DesignAnalysis, TestCase } from '../agents/schema.js';
import { scaffoldPlaywrightProject } from '../playwright/scaffold.js';

export interface PipelineAssets {
  analysis: DesignAnalysis;
  testCases: TestCase[];
  files: { path: string; content: string }[];
}

/**
 * End-to-end pipeline:
 *   1. Connect to Figma via MCP and pull the design (JSON + frame renders).
 *   2. AnalysisAgent reads the design.
 *   3. TestCaseAgent emits the test-case list (also written as markdown).
 *   4. AutomationAgent emits Playwright+TS files, scaffolded into a runnable project.
 */
export async function runPipeline(config: Config): Promise<PipelineAssets> {
  const llm = new OpenRouterClient(config);
  const figma = new FigmaMcp(config);

  console.log(`[*] Connecting to Figma MCP server (${config.figmaMcpCommand} ${config.figmaMcpArgs.join(' ')})...`);
  await figma.connect();
  console.log(`[*] Connected. Server tools: ${figma.toolList().join(', ')}.`);

  let analysis: DesignAnalysis;
  let testCases: TestCase[];
  let files: { path: string; content: string }[] = [];

  try {
    // --- Stage 1: fetch design ------------------------------------------
    if (!config.figmaFileKey) {
      throw new Error(
        'Set FIGMA_FILE_KEY in .env (the file key from your Figma URL, e.g. https://www.figma.com/design/<KEY>/...).',
      );
    }
    const imagesDir = join(config.playwrightOutputDir, '.figma-images');
    const { material } = await fetchFigmaMaterial(
      figma,
      config.figmaFileKey,
      config.designSeries ?? [],
      imagesDir,
    );
    console.log(
      `[*] Loaded design${material.images.length > 0 ? ` + ${material.images.length} rendered frame(s)` : ''}.`,
    );

    // --- Stage 2: analysis ------------------------------------------------
    console.log(`[*] [Agent 1/3] Analyzing design with ${config.model}...`);
    analysis = await new AnalysisAgent(llm, config.model).analyze(material);
    console.log(`    Product: "${analysis.productName}" | ${analysis.keyElements.length} elements, ${analysis.interactions.length} behaviors.`);

    // --- Stage 3: test cases ----------------------------------------------
    console.log(`[*] [Agent 2/3] Generating test cases...`);
    testCases = await new TestCaseAgent(llm, config.model).generate(analysis);
    console.log(`    Wrote ${testCases.length} test cases.`);
    await writeTestcaseMarkdown(config, analysis, testCases);

    // --- Stage 4: automation ---------------------------------------------
    console.log(`[*] [Agent 3/3] Generating Playwright + TypeScript automation...`);
    const files = await new AutomationAgent(llm, config.model).generate(testCases, config.appBaseUrl);
    console.log(`    Emitted ${files.length} source files.`);

    await scaffoldPlaywrightProject(config, files);
    console.log(`[*] Done. Playwright project scaffolded at "${config.playwrightOutputDir}".`);
  } finally {
    await figma.disconnect();
  }

  return { analysis, testCases, files };
}

async function writeTestcaseMarkdown(
  config: Config,
  analysis: DesignAnalysis,
  testCases: TestCase[],
): Promise<void> {
  await mkdir(config.testcasesOutputDir, { recursive: true });
  const lines: string[] = [
    `# ${analysis.productName} — Test Cases`,
    '',
    analysis.purpose,
    '',
    `Generated by ${config.model}`,
    '',
  ];
  for (const tc of testCases) {
    lines.push(
      `## ${tc.id} [${tc.priority}] ${tc.title}`,
      '',
      tc.description,
      '',
      `**Page:** ${tc.page}`,
      '',
    );
    if (tc.preconditions.length) {
      lines.push('**Preconditions:**', ...tc.preconditions.map((p) => `- ${p}`), '');
    }
    lines.push('**Steps:**', '');
    tc.steps.forEach((s, i) => {
      const suffix = s.value !== undefined ? ` (value: ${s.value})` : '';
      lines.push(`${i + 1}. \`${s.type}\` ${s.action}${suffix}${s.selector ? ` — \`${s.selector}\`` : ''}`);
    });
    lines.push('');
  }
  const file = join(config.testcasesOutputDir, 'test-cases.md');
  await writeFile(file, lines.join('\n'), 'utf8');
  console.log(`    Test cases saved to ${file}`);
}