// Deterministic Playwright specs from saved coverage when the AS agent
// fails to call script_save (common with free models that stop at prose).

import { insertOne } from "../store";
import type { Coverage, Script, TestCase } from "../types";

function slug(title: string, index: number): string {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return `${String(index + 1).padStart(2, "0")}-${base || "case"}`;
}

function escapeString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function specForCase(tc: TestCase, index: number): { path: string; code: string } {
  const name = slug(tc.title, index);
  const steps = (tc.steps || [])
    .map(
      (s, i) =>
        `  // Step ${i + 1}: ${escapeString(s.action)}\n` +
        `  // Expected: ${escapeString(s.expected)}`
    )
    .join("\n");

  const code = `import { test, expect } from "@playwright/test";

/**
 * ${escapeString(tc.title)}
 * Priority: ${tc.priority} · Type: ${tc.testType} · Scenario: ${tc.scenarioType || "positive"}
 * ${escapeString(tc.description || "")}
 *
 * Generated by QAE2E fallback (AS did not call script_save).
 * Replace selectors / URLs with your app under test.
 */
test.describe(${JSON.stringify(tc.title)}, () => {
  test(${JSON.stringify(tc.title)}, async ({ page }) => {
    // TODO: set baseURL in playwright.config.ts
    await page.goto("/");

${steps || "  // No steps provided — add assertions for this case."}

    // Placeholder assertion so the suite is runnable; replace with real checks.
    await expect(page).toHaveTitle(/.+/);
  });
});
`;

  return { path: `tests/${name}.spec.ts`, code };
}

/** Build + persist standalone Playwright files from coverage. */
export function saveFallbackScripts(requirementId: string, coverage: Coverage): Script {
  const files = coverage.testCases.map((tc, i) => specForCase(tc, i));
  // Cap very large suites so Docker materialize stays reasonable.
  const capped = files.slice(0, 20);
  const script: Script = {
    id: crypto.randomUUID(),
    requirementId,
    coverageId: coverage.id,
    framework: "playwright",
    language: "typescript",
    files: capped,
    createdAt: new Date().toISOString(),
  };
  insertOne("scripts", script);
  return script;
}
