// Server-side Playwright + TypeScript POM builder.
// Free LLMs truncate script_save payloads — never trust the model for full frameworks.
// This module emits a complete, runnable suite from saved coverage.

import { insertOne } from "../store";
import type { Coverage, Script, TestCase } from "../types";

function looksLikeSauceDemo(coverage: Coverage): boolean {
  const blob = JSON.stringify(coverage).toLowerCase();
  return (
    blob.includes("saucedemo") ||
    blob.includes("swag labs") ||
    blob.includes("standard_user") ||
    blob.includes("secret_sauce") ||
    blob.includes("locked_out_user")
  );
}

function packageJson(): string {
  return `${JSON.stringify(
    {
      name: "qae2e-generated-automation",
      private: true,
      version: "1.0.0",
      scripts: {
        test: "playwright test",
        "test:headed": "playwright test --headed",
        "test:ui": "playwright test --ui",
        "test:chromium": "playwright test --project=chromium",
        report: "playwright show-report",
      },
      devDependencies: {
        "@playwright/test": "1.51.0",
        "@types/node": "^22.10.0",
        typescript: "^5.7.0",
      },
    },
    null,
    2
  )}\n`;
}

function tsconfigJson(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "commonjs",
        lib: ["ES2022", "DOM"],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        rootDir: ".",
        baseUrl: ".",
      },
      include: ["tests/**/*.ts", "playwright.config.ts"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  )}\n`;
}

function playwrightConfig(baseURL: string): string {
  return `import { defineConfig, devices } from "@playwright/test";

/** Cross-browser Playwright config — generated by QAE2E (server-side). */
export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  timeout: 60_000,
  expect: { timeout: 10_000 },
  reporter: [
    ["list"],
    ["json", { outputFile: "test-results/results.json" }],
    ["html", { open: "never" }],
  ],
  use: {
    baseURL: process.env.BASE_URL || ${JSON.stringify(baseURL)},
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    actionTimeout: 15_000,
    navigationTimeout: 30_000,
    headless: true,
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
    { name: "firefox", use: { ...devices["Desktop Firefox"] } },
    { name: "webkit", use: { ...devices["Desktop Safari"] } },
  ],
});
`;
}

function basePage(): string {
  return `import { Page, Locator, expect } from "@playwright/test";

/** Shared UI helpers — feature pages extend this (playwright-e2e skill). */
export abstract class BasePage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  async navigate(path: string): Promise<void> {
    await this.page.goto(path);
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState("domcontentloaded");
  }

  async fillField(locator: Locator, value: string): Promise<void> {
    await locator.fill(value);
  }

  async clickElement(locator: Locator): Promise<void> {
    await locator.click();
  }

  async expectVisible(locator: Locator): Promise<void> {
    await expect(locator).toBeVisible();
  }

  async expectHidden(locator: Locator): Promise<void> {
    await expect(locator).toBeHidden();
  }

  async expectContainText(locator: Locator, expected: string | RegExp): Promise<void> {
    await expect(locator).toContainText(expected);
  }

  async expectURL(expected: string | RegExp): Promise<void> {
    await expect(this.page).toHaveURL(expected);
  }
}
`;
}

function sauceLoginPage(): string {
  return `import { Page, Locator } from "@playwright/test";
import { BasePage } from "./base.page";
import { Urls } from "../utils/test-data";

export class LoginPage extends BasePage {
  readonly usernameInput: Locator;
  readonly passwordInput: Locator;
  readonly loginButton: Locator;
  readonly errorMessage: Locator;

  constructor(page: Page) {
    super(page);
    this.usernameInput = page.getByPlaceholder("Username");
    this.passwordInput = page.getByPlaceholder("Password");
    this.loginButton = page.getByRole("button", { name: "Login" });
    this.errorMessage = page.locator("[data-test=\\"error\\"]");
  }

  async goto(): Promise<void> {
    await this.navigate(Urls.BASE);
  }

  async loginAs(username: string, password: string): Promise<void> {
    await this.fillField(this.usernameInput, username);
    await this.fillField(this.passwordInput, password);
    await this.clickElement(this.loginButton);
  }

  async expectLoginPageVisible(): Promise<void> {
    await this.expectVisible(this.usernameInput);
    await this.expectVisible(this.passwordInput);
    await this.expectVisible(this.loginButton);
  }

  async expectLoginError(expected: string | RegExp): Promise<void> {
    await this.expectVisible(this.errorMessage);
    await this.expectContainText(this.errorMessage, expected);
  }

  async expectStillOnLogin(): Promise<void> {
    await this.expectLoginPageVisible();
    await this.expectURL(/saucedemo\\.com\\/?$/);
  }
}
`;
}

function sauceInventoryPage(): string {
  return `import { Page, Locator } from "@playwright/test";
import { BasePage } from "./base.page";
import { Urls } from "../utils/test-data";

export class InventoryPage extends BasePage {
  readonly title: Locator;
  readonly cartBadge: Locator;
  readonly sortSelect: Locator;
  readonly menuButton: Locator;
  readonly logoutLink: Locator;
  readonly items: Locator;

  constructor(page: Page) {
    super(page);
    this.title = page.locator(".title");
    this.cartBadge = page.locator(".shopping_cart_badge");
    this.sortSelect = page.locator("[data-test=\\"product-sort-container\\"]");
    this.menuButton = page.getByRole("button", { name: "Open Menu" });
    this.logoutLink = page.getByRole("link", { name: "Logout" });
    this.items = page.locator(".inventory_item");
  }

  async expectLoaded(): Promise<void> {
    await this.expectURL(Urls.INVENTORY);
    await this.expectContainText(this.title, "Products");
    await this.expectVisible(this.sortSelect);
  }

  async expectProductCountAtLeast(n: number): Promise<void> {
    await this.page.waitForSelector(".inventory_item");
    const count = await this.items.count();
    if (count < n) throw new Error(\`Expected >= \${n} products, found \${count}\`);
  }

  async expectCartBadge(count: number): Promise<void> {
    if (count === 0) {
      await this.expectHidden(this.cartBadge);
      return;
    }
    await this.expectContainText(this.cartBadge, String(count));
  }

  async logout(): Promise<void> {
    await this.clickElement(this.menuButton);
    await this.clickElement(this.logoutLink);
  }
}
`;
}

function sauceFixture(): string {
  return `import { test as base } from "@playwright/test";
import { LoginPage } from "../pages/login.page";
import { InventoryPage } from "../pages/inventory.page";

type AppFixtures = {
  loginPage: LoginPage;
  inventoryPage: InventoryPage;
};

export const test = base.extend<AppFixtures>({
  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },
  inventoryPage: async ({ page }, use) => {
    await use(new InventoryPage(page));
  },
});

export { expect } from "@playwright/test";
`;
}

function saucePagesIndex(): string {
  return `export { BasePage } from "./base.page";
export { LoginPage } from "./login.page";
export { InventoryPage } from "./inventory.page";
`;
}

function sauceSpecFromCases(cases: TestCase[]): string {
  const lines: string[] = [];
  lines.push(`import { test, expect } from "../../fixtures/test.fixture";`);
  lines.push(`import { Credentials, ErrorMessages, Urls } from "../../utils/test-data";`);
  lines.push("");
  lines.push(`/** SauceDemo auth specs from coverage (${cases.length} cases). Playwright TS UI only. */`);
  lines.push(`test.describe("SauceDemo authentication", () => {`);

  const has = (re: RegExp) => cases.some((c) => re.test(c.title));

  if (has(/standard|successful login/i) || cases.length) {
    lines.push(`  test("Standard user login lands on inventory @smoke", async ({ loginPage, inventoryPage }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.expectLoginPageVisible();`);
    lines.push(`    await loginPage.loginAs(Credentials.STANDARD_USER, Credentials.PASSWORD);`);
    lines.push(`    await inventoryPage.expectLoaded();`);
    lines.push(`    await inventoryPage.expectProductCountAtLeast(6);`);
    lines.push(`    await inventoryPage.expectCartBadge(0);`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/locked/i) || cases.length) {
    lines.push(`  test("Locked out user shows lockout error @smoke", async ({ loginPage }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.loginAs(Credentials.LOCKED_OUT_USER, Credentials.PASSWORD);`);
    lines.push(`    await loginPage.expectLoginError(ErrorMessages.LOCKED_OUT);`);
    lines.push(`    await loginPage.expectStillOnLogin();`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/invalid/i) || cases.length) {
    lines.push(`  test("Invalid credentials show error @regression", async ({ loginPage }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.loginAs(Credentials.INVALID_USER, Credentials.PASSWORD);`);
    lines.push(`    await loginPage.expectLoginError(ErrorMessages.INVALID_CREDENTIALS);`);
    lines.push(`  });`);
    lines.push("");
    lines.push(`  test("Empty username shows required error @regression", async ({ loginPage, page }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await page.getByRole("button", { name: "Login" }).click();`);
    lines.push(`    await loginPage.expectLoginError(ErrorMessages.USERNAME_REQUIRED);`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/logout/i) || cases.length) {
    lines.push(`  test("Logout clears session and returns to login @smoke", async ({ loginPage, inventoryPage, page }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.loginAs(Credentials.STANDARD_USER, Credentials.PASSWORD);`);
    lines.push(`    await inventoryPage.expectLoaded();`);
    lines.push(`    await inventoryPage.logout();`);
    lines.push(`    await loginPage.expectLoginPageVisible();`);
    lines.push(`    await expect(page).toHaveURL(Urls.BASE);`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/problem/i)) {
    lines.push(`  test("Problem user reaches inventory @regression", async ({ loginPage, inventoryPage }) => {`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.loginAs(Credentials.PROBLEM_USER, Credentials.PASSWORD);`);
    lines.push(`    await inventoryPage.expectLoaded();`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/performance|glitch/i)) {
    lines.push(`  test("Performance glitch user eventually reaches inventory @regression", async ({ loginPage, inventoryPage }) => {`);
    lines.push(`    test.setTimeout(90_000);`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.loginAs(Credentials.PERFORMANCE_GLITCH_USER, Credentials.PASSWORD);`);
    lines.push(`    await inventoryPage.expectLoaded();`);
    lines.push(`  });`);
    lines.push("");
  }

  if (has(/responsive|mobile/i)) {
    lines.push(`  test("Login page usable on mobile viewport @regression", async ({ loginPage, inventoryPage, page }) => {`);
    lines.push(`    await page.setViewportSize({ width: 375, height: 667 });`);
    lines.push(`    await loginPage.goto();`);
    lines.push(`    await loginPage.expectLoginPageVisible();`);
    lines.push(`    await loginPage.loginAs(Credentials.STANDARD_USER, Credentials.PASSWORD);`);
    lines.push(`    await inventoryPage.expectLoaded();`);
    lines.push(`  });`);
    lines.push("");
  }

  lines.push(`});`);
  lines.push("");
  return lines.join("\n");
}

function sauceData(): string {
  return `export const Credentials = {
  STANDARD_USER: "standard_user",
  LOCKED_OUT_USER: "locked_out_user",
  PROBLEM_USER: "problem_user",
  PERFORMANCE_GLITCH_USER: "performance_glitch_user",
  INVALID_USER: "invalid_user",
  PASSWORD: "secret_sauce",
  WRONG_PASSWORD: "wrong_password",
} as const;

export const Urls = {
  BASE: "/",
  INVENTORY: "/inventory.html",
  CART: "/cart.html",
  CHECKOUT_STEP_ONE: "/checkout-step-one.html",
  CHECKOUT_STEP_TWO: "/checkout-step-two.html",
  CHECKOUT_COMPLETE: "/checkout-complete.html",
} as const;

export const ErrorMessages = {
  INVALID_CREDENTIALS:
    "Epic sadface: Username and password do not match any user in this service",
  LOCKED_OUT: "Epic sadface: Sorry, this user has been locked out.",
  USERNAME_REQUIRED: "Epic sadface: Username is required",
} as const;

export const Products = {
  BACKPACK: "Sauce Labs Backpack",
} as const;
`;
}

function genericFeatureName(coverage: Coverage): string {
  const raw = coverage.module || coverage.product || "App";
  const parts = raw.replace(/[^a-zA-Z0-9]+/g, " ").trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return "App";
  return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join("");
}

function genericData(baseURL: string): string {
  return `export const Urls = {
  HOME: "/",
  BASE: process.env.BASE_URL || ${JSON.stringify(baseURL)},
} as const;

export const Credentials = {
  VALID_USER: process.env.TEST_USER || "user@example.com",
  VALID_PASSWORD: process.env.TEST_PASSWORD || "Password123!",
} as const;
`;
}

function genericPage(feature: string): string {
  return `import { Page, Locator } from "@playwright/test";
import { BasePage } from "./base.page";
import { Urls } from "../utils/test-data";

export class ${feature}Page extends BasePage {
  readonly heading: Locator;
  readonly primaryAction: Locator;

  constructor(page: Page) {
    super(page);
    this.heading = page.getByRole("heading").first();
    this.primaryAction = page.getByRole("button").first();
  }

  async goto(): Promise<void> {
    await this.navigate(Urls.HOME);
  }

  async expectLoaded(): Promise<void> {
    await this.expectVisible(this.heading);
  }

  async clickPrimaryAction(): Promise<void> {
    await this.clickElement(this.primaryAction);
  }
}
`;
}

function genericFixture(feature: string): string {
  const prop = `${feature.charAt(0).toLowerCase()}${feature.slice(1)}Page`;
  return `import { test as base } from "@playwright/test";
import { ${feature}Page } from "../pages/${feature.toLowerCase()}.page";

type AppFixtures = { ${prop}: ${feature}Page };

export const test = base.extend<AppFixtures>({
  ${prop}: async ({ page }, use) => {
    await use(new ${feature}Page(page));
  },
});

export { expect } from "@playwright/test";
`;
}

function genericSpec(feature: string, cases: TestCase[]): string {
  const prop = `${feature.charAt(0).toLowerCase()}${feature.slice(1)}Page`;
  const tests = cases
    .slice(0, 12)
    .map((tc) => {
      const tag = tc.priority === "high" ? "@smoke" : "@regression";
      return `  test(${JSON.stringify(`${tc.title} ${tag}`)}, async ({ ${prop} }) => {
    await ${prop}.goto();
    await ${prop}.expectLoaded();
  });`;
    })
    .join("\n\n");

  return `import { test } from "../../fixtures/test.fixture";

test.describe(${JSON.stringify(`${feature} UI`)}, () => {
${tests}
});
`;
}

function inferBaseURL(coverage: Coverage): string {
  const blob = JSON.stringify(coverage);
  if (/saucedemo\.com/i.test(blob) || /saucedemo/i.test(blob)) return "https://www.saucedemo.com";
  const m = blob.match(/https?:\/\/[^\s"'\\]+/);
  return m ? m[0].replace(/\/$/, "") : "http://localhost:3000";
}

/** Build complete POM file set from coverage (never truncated). */
export function buildAutomationFiles(coverage: Coverage): Script["files"] {
  const baseURL = inferBaseURL(coverage);
  const cases = coverage.testCases || [];

  if (looksLikeSauceDemo(coverage)) {
    return [
      { path: "package.json", code: packageJson() },
      { path: "tsconfig.json", code: tsconfigJson() },
      { path: "playwright.config.ts", code: playwrightConfig(baseURL) },
      { path: "tests/pages/base.page.ts", code: basePage() },
      { path: "tests/pages/login.page.ts", code: sauceLoginPage() },
      { path: "tests/pages/inventory.page.ts", code: inventorySafe() },
      { path: "tests/pages/index.ts", code: saucePagesIndex() },
      { path: "tests/fixtures/test.fixture.ts", code: sauceFixture() },
      { path: "tests/utils/test-data.ts", code: sauceData() },
      { path: "tests/e2e/auth/login.spec.ts", code: sauceSpecFromCases(cases) },
    ];
  }

  const feature = genericFeatureName(coverage);
  const pageFile = `${feature.toLowerCase()}.page.ts`;
  return [
    { path: "package.json", code: packageJson() },
    { path: "tsconfig.json", code: tsconfigJson() },
    { path: "playwright.config.ts", code: playwrightConfig(baseURL) },
    { path: "tests/pages/base.page.ts", code: basePage() },
    { path: `tests/pages/${pageFile}`, code: genericPage(feature) },
    {
      path: "tests/pages/index.ts",
      code: `export { BasePage } from "./base.page";\nexport { ${feature}Page } from "./${feature.toLowerCase()}.page";\n`,
    },
    { path: "tests/fixtures/test.fixture.ts", code: genericFixture(feature) },
    { path: "tests/utils/test-data.ts", code: genericData(baseURL) },
    { path: `tests/e2e/${feature.toLowerCase()}/${feature.toLowerCase()}.spec.ts`, code: genericSpec(feature, cases) },
  ];
}

function inventorySafe(): string {
  return sauceInventoryPage();
}

/** Persist framework and return Script artifact. */
export function saveFallbackScripts(requirementId: string, coverage: Coverage): Script {
  const files = buildAutomationFiles(coverage);
  const script: Script = {
    id: crypto.randomUUID(),
    requirementId,
    coverageId: coverage.id,
    framework: "playwright",
    language: "typescript",
    files,
    createdAt: new Date().toISOString(),
  };
  insertOne("scripts", script);
  return script;
}
